name: langchain_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  # Add system-level file-magic
  - file
  - libmagic
  - pip:
    - langchain==0.0.284
    - python-dotenv==1.0.0
    - streamlit==1.22.0
    - unstructured==0.9.2
    - tiktoken==0.4.0
    - faiss-cpu==1.7.4
    - python-magic==0.4.27
    - openai==0.28.0